/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import controleur.EnumTypeEcran;
import controleur.Session;
import controleur.TraiterAjoutPanierResponse;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import metier.Client;
import metier.Commande;
import metier.Produit;

public class EcranAccueilPerso extends javax.swing.JFrame {

    /**
     * Creates new form EcranAccueil
     */
    public EcranAccueilPerso() {
        initComponents();
    }
    public EcranAccueilPerso(final Session laSession, final Client client, final Produit produit) {
        initComponents();
        this.setTitle("French Chic - Produit du jour");
        this.setSize(650, 500);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        bonjourTexte.setText("Bonjour "+client.getPrenom()+" "+client.getNom()+" !");
        produitDuJourTexte.setText("Le produit du jour est un \""+ produit.getNom() + "\" au prix de " + produit.getPrix() + " Euros");
        nomProduit.setText(produit.getNom());
        stockLabel.setText("Stock : "+produit.getQuantiteEnStock());
        prixLabel.setText("Prix : "+produit.getPrix());
        
        ajouterProduit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor((JButton) e.getSource());
                Integer intg = new Integer(quantiteField.getText());
                TraiterAjoutPanierResponse reponse = laSession.traiterAjoutPanier(produit, intg);
                if (reponse.laCommande!=null){
                    if (reponse.typeEcran == EnumTypeEcran.ECRAN_PANIER) {
                        frame.setVisible(false);
                        afficherEcranPanier(reponse.laCommande);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bonjourTexte = new javax.swing.JLabel();
        ajouterProduit = new javax.swing.JButton();
        produitDuJourTexte = new javax.swing.JLabel();
        nomProduit = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        quantiteLabel = new javax.swing.JLabel();
        quantiteField = new javax.swing.JTextField();
        stockLabel = new javax.swing.JLabel();
        prixLabel = new javax.swing.JLabel();
        accueilPersoButton = new javax.swing.JButton();
        cataogueButton = new javax.swing.JButton();
        panierButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 241, 241));

        jPanel1.setBackground(new java.awt.Color(242, 0, 243));

        title.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("French Chic");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bonjourTexte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bonjourTexte.setText("Bonjour Marie Dupond !");

        ajouterProduit.setText("Ajouter le produit du jour au panier");

        produitDuJourTexte.setText("Le produit du jour est");

        nomProduit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomProduit.setText("Pantalon cargo");

        description.setText("Tissu de qualité supérieure, il est confortable à porter et vous donne un look d'enfer");
        description.setToolTipText("");
        description.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        description.setVerifyInputWhenFocusTarget(false);

        quantiteLabel.setText("Quantité :");

        stockLabel.setText("Stock : 34");

        prixLabel.setText("Prix : 34");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockLabel)
                    .addComponent(prixLabel)
                    .addComponent(produitDuJourTexte)
                    .addComponent(nomProduit)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(quantiteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bonjourTexte)
                    .addComponent(ajouterProduit))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bonjourTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produitDuJourTexte)
                .addGap(33, 33, 33)
                .addComponent(nomProduit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(stockLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prixLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantiteLabel)
                    .addComponent(quantiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ajouterProduit)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        stockLabel.getAccessibleContext().setAccessibleName("Stock");

        accueilPersoButton.setText("Accueil");

        cataogueButton.setText("Catalogue");

        panierButton.setText("Panier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accueilPersoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cataogueButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panierButton)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accueilPersoButton)
                    .addComponent(cataogueButton)
                    .addComponent(panierButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcranAccueilPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcranAccueilPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcranAccueilPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcranAccueilPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcranAccueilPerso().setVisible(true);
            }
        });
    }
    
    private static void afficherEcranPanier(Commande laCommande) {
        EcranPanier ecranPanier = new EcranPanier(laCommande);
        ecranPanier.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueilPersoButton;
    private javax.swing.JButton ajouterProduit;
    private javax.swing.JLabel bonjourTexte;
    private javax.swing.JButton cataogueButton;
    private javax.swing.JLabel description;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomProduit;
    private javax.swing.JButton panierButton;
    private javax.swing.JLabel prixLabel;
    private javax.swing.JLabel produitDuJourTexte;
    private javax.swing.JTextField quantiteField;
    private javax.swing.JLabel quantiteLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
